zhaoyuuu/violet-design

- .eslintrc.js
- package-lock.json
- package.json
- src/App.tsx
- src/index.tsx
> feat!: configure eslint

- .prettierrc
- .prettierrc.js
- src/App.tsx
- src/index.tsx
> feat!: configure prettier

- src/App.scss
- src/App.tsx
> feat: modify App.tsx

- README.md
> feat: initialize readme

- .husky/pre-commit
- package-lock.json
- package.json
- src/App.tsx
> Initialize husky

- src/App.scss
- src/App.tsx
- src/components/Menu/menu.scss
- src/components/Menu/menu.tsx
- src/components/Menu/menuItem.tsx
- src/components/Menu/subMenu/subMenu.scss
- src/components/Menu/subMenu/subMenu.tsx
> Menu component

- src/App.tsx
- src/components/Menu/menu.stories.tsx
- src/components/Menu/menu.tsx
- src/components/Menu/menuItem.tsx
- src/components/Menu/subMenu/subMenu.tsx
- src/stories/Page.tsx
> feat: add the story of menu

- src/App.tsx
- src/components/Radio/radio.tsx
> feat: single radio feature, just a git push test

- src/components/Menu/menu.scss
- src/components/Menu/menuItem.tsx
- src/components/Menu/subMenu/subMenu.tsx
> fix: menu style

- src/App.tsx
- src/components/InputNumber/inputNumber.scss
- src/components/InputNumber/inputNumber.tsx
- src/styles/_variables.scss
> feat: number input

- src/App.tsx
- src/components/Input/Input.scss
- src/components/Input/Input.tsx
> feat: add Input component

- package-lock.json
- package.json
- src/components/Radio/radio.test.tsx
- src/components/Radio/radio.tsx
- src/components/Radio/radioGroup.test.tsx
fix: radio checked without onChange bug
> feat: radio test

- src/App.tsx
- src/components/Button/button.stories.tsx
- src/components/Button/button.tsx
- src/components/Form/form.stories.tsx
- src/components/Form/form.tsx
- src/components/Form/formItem.tsx
> feat!:add basic form

- src/styles/_mixin.scss
包装了一下react的cssTransition，在select组件中需要用到动画
> feat: add animation effect

- src/App.tsx
- src/components/Cascader/_style.scss
- src/components/Cascader/cascader.tsx
- src/components/InputNumber/_style.scss
- src/components/InputNumber/inputNumber.stories.tsx
- src/components/InputNumber/inputNumber.test.tsx
- src/components/InputNumber/inputNumber.tsx
- src/components/Menu/_style.scss
- src/components/Menu/menu.tsx
- src/components/Menu/menuItem.tsx
- src/components/Menu/subMenu/_style.scss
- src/components/Menu/subMenu/subMenu.tsx
- src/styles/index.scss
> Input number

- src/App.tsx
- src/components/Form/form.stories.tsx
- src/components/Input/Input.tsx
- src/components/Input/_style.scss
- src/components/Input/input.stories.tsx
- src/styles/_variables.scss
增加Input组件的story, 和优化样式
修改部分bug
> Input optimization

- src/components/Select/_style.scss
- src/components/Select/index.tsx
- src/components/Select/option.tsx
- src/components/Select/select.stories.tsx
- src/components/Select/select.tsx
- src/styles/index.scss
> feat: add select component

- src/components/Form/form.stories.tsx
- src/components/Select/_style.scss
- src/components/Select/index.tsx
- src/components/Select/select.stories.tsx
- src/components/Select/select.test.tsx
- src/components/Select/select.tsx
BREAKING CHANGE: modify the usage mode of option.tsx according to antd
> fix!: import option as select's props 

- src/components/Input/input.stories.tsx
- src/components/Input/input.tsx
- src/components/Radio/radioGroup.tsx
- src/components/Select/select.stories.tsx
- src/components/Select/select.tsx
增加select功能：三种大小的select。
在增加的过程中，根据需求稍微修改了radio 和 input组件
> feat: add 'different size select'

- src/components/Select/select.stories.tsx
- src/components/Select/select.test.tsx
- src/components/Select/select.tsx
> feat: add 'search select'

- package-lock.json
- src/components/CheckBox/_style.scss
> fix:checkbox style

- src/components/Grid/grid/RowContext.tsx
- src/components/Grid/grid/_style.scss
- src/components/Grid/grid/col.tsx
- src/components/Grid/grid/index.tsx
- src/components/Grid/grid/row.tsx
- src/components/Grid/index.tsx
- src/components/Tabs/_style.scss
- src/styles/index.scss
feat:add grid & correct disabled tabs
> feat:add grid & correct disabled tabs

- src/components/Grid/story/grid.stories.tsx
- src/components/Icon/icon.stories.tsx
feat:add all icon story without style and fix grid story
> feat:add all icon story without style and fix grid story

- src/components/DatePicker/Picker.tsx
- src/components/DatePicker/RangeDatePicker/RangeDatePicker.tsx
> feat:add datepicker transtion

- src/components/DatePicker/stories/DatePicker.stories.tsx
- src/components/DatePicker/stories/RangePicker.stories.tsx
feat: add decorator to the datepicker story
> feat: add decorator to the datepicker story

- src/components/Calendar/CalendarSelectedController.tsx
- src/components/Calendar/_style.scss
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/RangeDatePicker/RangeDatePicker.tsx
- src/components/RangeDatePicker/RangePicker.stories.tsx
- src/components/RangeDatePicker/RangePickerInput.tsx
> feat:optimize datepicker style

- package-lock.json
- src/components/Calendar/Calendar.stories.tsx
- src/components/Calendar/CalenderComponents/CalendarContainer.tsx
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/RangeDatePicker/RangePicker.stories.tsx
feat:optimize storybook & fix bug
> feat:optimize storybook & fix bug

- .storybook/main.js
- .storybook/preview.js
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
> feat:rollback storybook

- src/components/Switcher/switcher.stories.tsx
> feat : optimize switch story
